blog/articles/routes.py
# from sqlalchemy import and_

from datetime import datetime
from flask import Flask, render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required

from .forms import CreateArticleForm
from blog.models import Article, Category
from blog import db

articles_bp = Blueprint('articles_bp', __name__)

@articles_bp.route('/createarticle')
@login_required
def create_article():
    form = CreateArticleForm()
    form.categories.choices = [(c.id, c.title) for c in Category.query.order_by(Category.id.asc()).all()]

    return render_template('createarticle.html', form = form)

@articles_bp.route('/createarticle', methods=['POST'])
@login_required
def create_article_post():
    form = CreateArticleForm(request.form)
    form.categories.choices = [(c.id, c.title) for c in Category.query.order_by(Category.id.asc()).all()]

    #article = Article.query.filter(and_(Article.category_id == form.categories.data, Article.title == str(form.title.data))).first()

    if form.validate(): # and not article
        new_article = Article(
            title = str(form.title.data), 
            content = str(form.content.data), 
            owner_id = current_user.id, 
            category_id = form.categories.data,
            created_at = datetime.now(),
            updated_at = datetime.now()
        )
        db.session.add(new_article)
        db.session.commit()

        return redirect(url_for('dashboard_bp.dashboard'))

    flash('Article are not created, input was not valid!')
    return redirect(url_for('article_bp.create_article'))


@articles_bp.route('/deletearticle/<int:article_id>', methods=['POST'])
@login_required
def delete_article(article_id):
    article = Article.query.filter_by(id = article_id, owner_id = current_user.id).first()

    if article:
        db.session.delete(article)
        db.session.commit()

    return redirect(url_for('dashboard_bp.dashboard'))

@articles_bp.route('/article/update/<article_id>', methods=['GET', 'POST'])
@login_required
def update_article(article_id):
    article = Article.query.get_or_404(article_id)
    
    form = CreateArticleForm(request.form)
    form.categories.choices = [(c.id, c.title) for c in Category.query.order_by(Category.id.asc()).all()]

    if article:
        if request.method == 'GET':
            form.title.data = article.title
            form.content.data = article.content

        if request.method == 'POST' and form.validate():
            index = int( form.categories.data )
            category_id = form.categories.choices[index - 1][0]

            article.title = str(form.title.data)
            article.content = str(form.content.data)
            article.category_id = category_id
            article.updated_at = datetime.now()

            db.session.commit()
            
            return redirect(url_for('dashboard_bp.single_article', article_id = article_id))

    return render_template('updatearticle.html', form = form)

blog/categories/routes.py
from flask import Flask, render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required

from .forms import CreateCategoryForm
from blog.models import Category
from blog import db

categories_bp = Blueprint('categories_bp', __name__)

@categories_bp.route('/category')
@login_required
def add_category():
    form = CreateCategoryForm()
    return render_template('createcategory.html', form = form)

@categories_bp.route('/category', methods=['POST'])
@login_required
def add_category_post():
    form = CreateCategoryForm(request.form)

    if form.validate():
        new_category = Category(title = request.form.get('title').lower())
        db.session.add(new_category)
        db.session.commit()
            
        return redirect(url_for('dashboard_bp.dashboard'))

    for error in form.errors.items():
        flash(error[0].capitalize() + ': '+ str(error[1][0]))

    return redirect(url_for('categories_bp.add_category'))

blog/dashboard/routes.py
from flask import Flask, render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required

from blog.models import Article
from blog import app, db

dashboard_bp = Blueprint('dashboard_bp', __name__)

@dashboard_bp.route('/search', methods=['GET'])
@login_required
def search():
    keyword = request.args.get('query')
    results = Article.query.msearch(keyword, fields=['title', 'content'], limit=10)

    return render_template('dashboard.html', search_results = results)

@dashboard_bp.route('/single/<int:article_id>')
@login_required
def single_article(article_id):
    article = Article.query.get_or_404(article_id)

    return render_template('single.html', post = Article.marshmallow_data(article))

@dashboard_bp.route('/userarticles/<int:user_id>')
@login_required
def user_articles(user_id):
    articles = Article.query.filter_by(owner_id = user_id).all()

    output = []
    for article in articles:
        output.append( Article.marshmallow_data(article) )

    return render_template('userarticles.html', posts = output)

@dashboard_bp.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    articles = Article.query.order_by(Article.updated_at.desc()).all()

    output = []
    for article in articles:
        output.append( Article.marshmallow_data(article) )

    return render_template('dashboard.html', posts = output)

blog/users/routes.py
from flask import Flask, render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

from flask_mail import Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer

from blog.users.forms import LoginForm, RegistrationForm, RequestResetForm, ResetPasswordForm
from blog.models import User
from blog import db, app, mail

users_bp = Blueprint('users_bp', __name__)

@users_bp.route('/register')
def register_user():
    form = RegistrationForm()
    
    return render_template('register.html', form = form)

@users_bp.route('/register', methods=['POST'])
def register_user_post():
    if current_user.is_authenticated:
        return redirect( url_for('dashboard_bp.dashboard') )

    form = RegistrationForm(request.form)
    if form.validate():
        hashed_password = generate_password_hash(form.password.data, method = 'pbkdf2:sha256')
        
        new_user = User(
            email = request.form.get('email').lower(),
            first_name = request.form.get('first_name').lower(),
            last_name = request.form.get('last_name').lower(),
            created_at = datetime.now(),
            password = hashed_password
        )
        db.session.add(new_user)
        db.session.commit()

        send_confirmation_email(new_user.email)

        flash('The confirmation link is sent.')

        return redirect(url_for('users_bp.login'))

    for error in form.errors.items():
        flash(error[0].capitalize() + ': '+ str(error[1][0]))
        
    return redirect(url_for('users_bp.register_user'))

@users_bp.route('/')
@users_bp.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard_bp.dashboard'))

    form = LoginForm()
    return render_template('login.html', form = form)

@users_bp.route('/', methods=['POST'])
@users_bp.route('/login', methods=['POST'])
def login_post():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard_bp.dashboard'))

    form = LoginForm(request.form)

    user = User.query.filter_by(email = request.form.get('email').lower()).first()

    if user and form.validate() and check_password_hash(user.password, request.form.get('password')):
        login_user(user)
        return redirect(url_for('dashboard_bp.dashboard'))

    flash('You have entered an invalid username or password!')
    return redirect(url_for('users_bp.login'))

@users_bp.route('/logout')
@login_required
def logout():
    logout_user()

    return redirect(url_for('users_bp.login'))

@users_bp.route("/reset_password")
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard_bp.dashboard'))

    return render_template('reset_request.html', form = RequestResetForm())

@users_bp.route("/reset_password", methods=['POST'])
def reset_request_post():
    form = RequestResetForm(request.form)

    user = User.query.filter_by(email = request.form.get('email')).first()

    if user and form.validate():
        send_reset_email(request.form.get('email').lower())
        flash('An email has been sent with instructions to reset your password.')
    else:
        flash('There is no account with that email. You must register first.')

    return redirect(url_for('users_bp.login'))

@users_bp.route('/reset/<token>')
def reset_with_token(token):
    form = ResetPasswordForm()

    return render_template('reset_password.html', form = form, token = token)

@users_bp.route('/reset/<token>', methods=['POST'])
def reset_with_token_post(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=1800)
    except:
        flash('The password reset link is invalid or has expired.', 'error')
        return redirect(url_for('users_bp.login'))

    form = ResetPasswordForm(request.form)
    
    if form.validate():
        user = User.query.filter_by(email = email).first()
        
        user.password = generate_password_hash(request.form.get('password'), method = 'pbkdf2:sha256')
        db.session.commit()
        
        flash('Your password has been updated!')
        return redirect(url_for('users_bp.login'))

    for error in form.errors.items():
        flash(error[0].capitalize() + ': '+ str(error[1][0]))

    return redirect(url_for('users_bp.reset_with_token', token = token))


@users_bp.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=1800)
    except:
        flash('The confirmation link is invalid or has expired.')
        return redirect(url_for('users_bp.login'))

    user = User.query.filter_by(email = email).first()

    if user.email_confirmed:
        flash('Account already confirmed. Please login.')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        
        flash('Thank you for confirming your email address!')

    return redirect(url_for('dashboard_bp.dashboard'))

def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users_bp.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'), _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url = confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)

def send_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users_bp.reset_with_token',
        token = password_reset_serializer.dumps(user_email, salt='password-reset-salt'), _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url = password_reset_url)

    send_email('Password Reset Requested', [user_email], html)

templates/createarticle.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('dashboard_bp.dashboard') }}">Back</a></li>
</ul>

<div class="center">
    <form action="{{ url_for('articles_bp.create_article_post') }}" method="POST" class="pure-form pure-form-stacked">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Title</label>
                    {{ form.title(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Content</label>
                    {{ form.content(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Category</label>
                    {{ form.categories(class="pure-u-23-24") }}
                </div>
            </div>
            <button type="submit" class="pure-button pure-button-primary">Publish</button>
        </fieldset>
    </form>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="error-message">
    <span class="error-text">{{ messages[0] }}</span>
</div>
{% endif %}
{% endwith %}

{% endblock content %}

templates/createcategory.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('dashboard_bp.dashboard') }}">Back</a></li>
</ul>

<div class="center">
    <form action="{{ url_for('categories_bp.add_category_post') }}" method="POST" class="pure-form pure-form-stacked">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Category</label>
                    {{ form.title(class="pure-u-23-24") }}
                </div>
            </div>
            <button type="submit" class="pure-button pure-button-primary">Create</button>
        </fieldset>
    </form>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="error-message">
    <span class="error-text">{{ messages[0] }}</span>
</div>
{% endif %}
{% endwith %}

{% endblock content %}

templates/dashboard.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('users_bp.logout') }}">Logout ({{ current_user.first_name + ' ' + current_user.last_name }})</a></li>
    <li><a href="{{ url_for('dashboard_bp.dashboard') }}">Home</a></li>
    <li><a href="{{ url_for('categories_bp.add_category') }}">Category</a></li>
    <li><a href="{{ url_for('articles_bp.create_article') }}">Article</a></li>
</ul>

<div class="searchbtn">
    <form class="pure-form" method="GET" action="search">
        <input type="text" class="pure-input-rounded" name="query">
        <button type="submit" class="pure-button">Search</button>
    </form>
</div>

<div id="layout" class="pure-g">
    <div class="content pure-u-1 pure-u-md-3-4">
        {% for post in posts %}
        <div class="posts">
            <section class="post">
                <header class="post-header">
                    <p class="post-title"><a href="{{ url_for('dashboard_bp.single_article', article_id = post['article_id']) }}">{{ post['title'] }}</a></p>
                    <p class="post-meta">
                        By <a href="{{ url_for('dashboard_bp.user_articles', user_id = post['user_id']) }}" class="post-author">{{ post['first_name'] }} {{ post['last_name'] }}</a> under <a class="post-category post-category-design disablelinks" href="#">{{ post['category'] }}</a>
                    </p>
                </header>

                <h1 class="content-subhead">{{ post['updated_at'].strftime("%Y-%m-%d %H:%M:%S") }}</h1>

                <div class="post-description">
                    <p>
                        {{ post['content'] }}
                    </p>
                </div>

                {% if post.user_id == current_user.id %}
                <form method="POST" action="{{ url_for('articles_bp.delete_article', article_id = post['article_id']) }}" class="pure-form pure-form-stacked">
                    <button type="submit" class="pure-button pure-button-primary">Delete</button>
                </form>
                {% endif %}
            </section>
        </div>
        {% endfor %}
    </div>
</div>

<div id="layout" class="pure-g">
    <div class="content pure-u-1 pure-u-md-3-4">
        {% for res in search_results %}
        <div class="posts">
            <section class="post">
                <h1 class="content-subhead"></h1>

                <header class="post-header">
                    <h2 class="post-title">{{ res['title'] }}</h2>
                </header>

                <div class="post-description">
                    <p>
                        {{ res['content'] }}
                    </p>
                    <p class="post-meta">
                        <a class="post-category post-category-design" href="{{ url_for('dashboard_bp.single_article', article_id = res['id']) }}">More details...</a>
                    </p>
                </div>

                <h1 class="content-subhead"></h1>
            </section>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

templates/email_confirmation.html
{% extends "layout.html" %}
{% block content %}

Your account was successfully created.<br>
Please click the link below to confirm your email address and activate your account:<br>

<p>
    <a href="{{ confirm_url }}">{{ confirm_url }}</a>
</p>

{% endblock content %}

templates/email_password_reset.html
{% extends "layout.html" %}
{% block content %}

Please click the link below to reset your password:

<p>
    <a href="{{ password_reset_url }}">{{ password_reset_url }}</a>
</p>

{% endblock content %}

templates/layout.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-oAOxQR6DkCoMliIh8yFnu25d7Eq/PHS21PClpwjOTeU2jRSq11vu66rf90/cZr47" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mycss.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='posts.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title></title>
</head>
<body>

    {% block content %}{% endblock %}

</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block content %}

    <ul>
        <li><a href="{{ url_for('users_bp.register_user') }}">Sign up</a></li>
        <li><a href="{{ url_for('users_bp.reset_request') }}">Forgot password?</a></li>
    </ul>

<div class="center">
    <form action="{{ url_for('users_bp.login_post') }}" method="POST" class="pure-form pure-form-stacked">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Email</label>
                    {{ form.email(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Password</label>
                    {{ form.password(class="pure-u-23-24") }}
                </div>
            </div>
            <button type="submit" class="pure-button pure-button-primary">Log in</button>
        </fieldset>
    </form>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="error-message">
    <span class="error-text">{{ messages[0] }}</span>
</div>
{% endif %}
{% endwith %}

{% endblock content %}

templates/register.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('users_bp.login') }}">Log in</a></li>
</ul>

<div class="center">
    <form action="{{ url_for('users_bp.register_user_post') }}" method="POST" class="pure-form pure-form-stacked">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1 pure-u-md-1-3">
                    <label>First name</label>
                    {{ form.first_name(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Last name</label>
                    {{ form.last_name(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Email</label>
                    {{ form.email(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Password</label>
                    {{ form.password(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Confirm password</label>
                    {{ form.confirm_password(class="pure-u-23-24") }}
                </div>
            </div>
            <button type="submit" class="pure-button pure-button-primary">Register</button>
        </fieldset>
    </form>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="error-message">
    <span class="error-text">{{ messages[0] }}</span>
</div>
{% endif %}
{% endwith %}

{% endblock content %}

templates/reset_password.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('users_bp.login') }}">Log in</a></li>
</ul>

<div class="center">
    <form action="{{ url_for('users_bp.reset_with_token_post', token = token) }}" method="POST" class="pure-form pure-form-stacked">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Password</label>
                    {{ form.password(class="pure-u-23-24") }}
                </div>
            </div>
            <div class="pure-g">
                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Confirm password</label>
                    {{ form.confirm_password(class="pure-u-23-24") }}
                </div>
            </div>
            <button type="submit" class="pure-button pure-button-primary">Confirm</button>
        </fieldset>
    </form>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="error-message">
    <span class="error-text">{{ messages[0] }}</span>
</div>
{% endif %}
{% endwith %}

{% endblock content %}

templates/reset_request.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('users_bp.login') }}">Log in</a></li>
</ul>

<div class="center">
    <form action="{{ url_for('users_bp.reset_request_post') }}" method="POST" class="pure-form pure-form-stacked">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Email</label>
                    {{ form.email(class="pure-u-23-24") }}
                </div>
            </div>
            <button type="submit" class="pure-button pure-button-primary">Request</button>
        </fieldset>
    </form>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="error-message">
    <span class="error-text">{{ messages[0] }}</span>
</div>
{% endif %}
{% endwith %}

{% endblock content %}

templates/single.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('dashboard_bp.dashboard') }}">Home</a></li>
</ul>

<div id="layout" class="pure-g">
    <div class="content pure-u-1 pure-u-md-3-4">
        <div class="posts">
            <section class="post">
                <header class="post-header">
                    <p class="post-title"><a href="#" class="disablelinks">{{ post['title'] }}</a></p>
                    <p class="post-meta">
                        By <a href="#" class="post-author disablelinks">{{ post['first_name'] }} {{ post['last_name'] }}</a> under <a class="post-category post-category-design disablelinks" href="#">{{ post['category'] }}</a>
                    </p>
                </header>

                <h1 class="content-subhead">{{ post['updated_at'].strftime("%Y-%m-%d %H:%M:%S") }}</h1>

                <div class="post-description">
                    <p>
                        {{ post['content'] }}
                    </p>
                </div>

                {% if post.user_id == current_user.id %}
                <form method="GET" action="{{ url_for('articles_bp.update_article', article_id = post['article_id']) }}" class="pure-form pure-form-stacked">
                    <button type="submit" class="pure-button pure-button-primary">Update</button>
                </form>
                {% endif %}

            </section>
        </div>
    </div>
</div>

{% endblock content %}

templates/updatearticle.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('dashboard_bp.dashboard') }}">Back</a></li>
</ul>

<div class="center">
    <form action="" method="POST" class="pure-form pure-form-stacked">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="pure-g">
                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Title</label>
                    {{ form.title(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Content</label>
                    {{ form.content(class="pure-u-23-24") }}
                </div>

                <div class="pure-u-1 pure-u-md-1-3">
                    <label>Category</label>
                    {{ form.categories(class="pure-u-23-24") }}
                </div>
            </div>
            <button type="submit" class="pure-button pure-button-primary">Update</button>
        </fieldset>
    </form>
</div>

{% endblock content %}

templates/userarticles.html
{% extends "layout.html" %}
{% block content %}

<ul>
    <li><a href="{{ url_for('dashboard_bp.dashboard') }}">Home</a></li>
</ul>

<div id="layout" class="pure-g">
    <div class="content pure-u-1 pure-u-md-3-4">
        {% for post in posts %}
        <div class="posts">
            <section class="post">
                <header class="post-header">
                    <h1 class="post-title"><a href="{{ url_for('dashboard_bp.single_article', article_id = post['article_id']) }}">{{ post['title'] }}</a></h1>
                    <p class="post-meta">
                        By <a href="#" class="post-author">{{ post['first_name'] }} {{ post['last_name'] }}</a> under <a class="post-category post-category-design" href="#">{{ post['category'] }}</a>
                    </p>
                </header>

                <h1 class="content-subhead">{{ post['updated_at'].strftime("%Y-%m-%d %H:%M:%S") }}</h1>

                <div class="post-description">
                    <p>
                        {{ post['content'] }}
                    </p>
                </div>

                {% if post.user_id == current_user.id %}
                <form method="POST" action="{{ url_for('articles_bp.delete_article', article_id = post['article_id']) }}" class="pure-form pure-form-stacked">
                    <button type="submit" class="pure-button pure-button-primary">Delete</button>
                </form>
                {% endif %}
            </section>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}